import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Header, Footer } from "@/widgets";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${lato.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
